MODULE YOEDUST

USE PARKIND1, ONLY: JPIM, JPRB
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK, JPHOOK
USE YOMLUN,   ONLY: NULOUT

IMPLICIT NONE

SAVE 
! ------------------------------------------------------------------
!*** *YOEDUST* - ECE4 CLIMATOLOGIAL FIELD FOR DUST EMISSION SCHEME ! 
!                       Called in tm5m7_src_dust.F90
!     info:  
!                This module reads and interpolates climatological !
!                surface fields that used in Dust emission Scheme
!                Tegen et al., 2002. 
!     
!         :      Marios Chatziparaschos 
!                Barcelona Supercomputing Center 
!         :      26/06/2025        
! -----------------------------------------------------------------!-
TYPE :: TEAERC_DUST
!- based on SURFACE 2D (lat,lon) 1x1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: CULT,POTSRC
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: AREA
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: SOILPH1,SOILPH2,SOILPH3,SOILPH4,SOILPH5
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: LAI_MAX, LAI_AVG
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: Z0AM
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: SOILTYPE

!latitude and logitude in Degrees 
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)     :: LATD,LOND

! in radians
REAL(KIND=JPRB) :: LAT1 = 0.0_JPRB, LON1 = 0.0_JPRB
REAL(KIND=JPRB) :: DLAT = 0.0_JPRB, DLON = 0.0_JPRB
INTEGER(KIND=JPIM) :: NLAT = 0, NLON = 0

REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: Z0M
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: FPAR
!lon,lat,month

! Number of the Grouped fields for 2d-3d, numb-month
INTEGER(KIND=JPIM) :: NMONTH=0

! INTERPOLATED ARRAYS MAYBE DO NOT NEED IT but saved into the main  pointer
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TCULT, TSOILTYPE, TPOTSRC
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TAREA,  TZ0AM
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TSOILPH1, TSOILPH2, TSOILPH3, TSOILPH4, TSOILPH5
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TZ0M , TFPAR
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TLAI_MAX, TLAI_AVG
LOGICAL :: IS_INITIALISED = .FALSE.
LOGICAL :: IS_INTERPOLATED = .FALSE.

CONTAINS

PROCEDURE :: READ => SETUP_DUST_CLIM
PROCEDURE :: INTERPOLATION =>SU_DUST_FIELDS_INTERP
PROCEDURE :: FINALIZE => CLEANUP_DUST_CLIM 

END TYPE TEAERC_DUST

TYPE(TEAERC_DUST), POINTER :: YDUSTCLIM => NULL()

!==========================================================================================

CONTAINS 

SUBROUTINE SETUP_DUST_CLIM(SELF)
  USE YOMLUN, ONLY : NULOUT
  !------------
  CLASS(TEAERC_DUST), INTENT(INOUT) :: SELF
  
  CALL SU_DUST_FIELDS(SELF)
  WRITE(NULOUT,*) '2D FIELDS FOR DUST CLIMATOLOGY IS LOADED'
  SELF%IS_INITIALISED = .TRUE.
  
END SUBROUTINE SETUP_DUST_CLIM


SUBROUTINE SU_DUST_FIELDS(SELF_DUST)
!-----------------------------------------------------------------------
USE PARKIND1  , ONLY : JPIM, JPRB
USE EASY_NETCDF_READ_MPI,ONLY : NETCDF_FILE
USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN    , ONLY : NULERR
USE YOMLUN    , ONLY : NULOUT
USE YOMCST    , ONLY : RPI

IMPLICIT NONE

TYPE(TEAERC_DUST), INTENT(INOUT) :: SELF_DUST
! Expected dimension lengths for month, latitude and longitude
INTEGER(KIND=JPIM), PARAMETER :: IMONTH = 12
INTEGER(KIND=JPIM), PARAMETER :: ILAT   = 180 !61
INTEGER(KIND=JPIM), PARAMETER :: ILON   = 360 !120
! Full and base names of the aerosol climatology file
CHARACTER(len=:),ALLOCATABLE :: CL_FILE_NAME, CL_AER_CLIM_FILE 
!Temporary file containing the input of fields
! "DATA" directory
CHARACTER(LEN=512)  :: CLDIRECTORY
! The NetCDF file containing the input climatology
TYPE(NETCDF_FILE)  :: FILE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"
!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('YOEDUST:SU_DUST_CLIMATOLOGY',0,ZHOOK_HANDLE)

  !!CL_AER_CLIM_FILE = "onlinedust_v4_rmp.nc" 
  CL_AER_CLIM_FILE ="onlinedust_v4_rmp_dp.nc" !!! double precision
  CALL GET_ENVIRONMENT_VARIABLE("DATA",CLDIRECTORY)
  IF(CLDIRECTORY /= " ") THEN
    CL_FILE_NAME = TRIM(CLDIRECTORY) // "/ifsdata/" // CL_AER_CLIM_FILE
  ELSE
    CL_FILE_NAME = CL_AER_CLIM_FILE
  ENDIF
  CALL FILE%OPEN(TRIM(CL_FILE_NAME), IVERBOSE=4)
  CALL FILE%GET('lat', SELF_DUST%LATD)
  CALL FILE%GET('lon', SELF_DUST%LOND)
  CALL FILE%GET('cult', SELF_DUST%CULT)  
  CALL FILE%GET('lai_max', SELF_DUST%LAI_MAX)
  CALL FILE%GET('lai_avg', SELF_DUST%LAI_AVG)

  CALL FILE%GET('fpar', SELF_DUST%FPAR)
  IF (    SIZE(SELF_DUST%FPAR,1) /= ILON .OR. &
       &  SIZE(SELF_DUST%FPAR,2) /= ILAT .OR. &
       &  SIZE(SELF_DUST%FPAR,3) /= IMONTH) THEN
    WRITE(NULERR,*) 'Aerosols in', CL_FILE_NAME, 'must be dimensioned (', &
         &  ILON, ",", ILAT, ",", IMONTH, ")"
    CALL ABOR1("Error reading aerosol climatology NetCDF file")
  ENDIF
  CALL FILE%GET('potsrc', SELF_DUST%POTSRC)
  CALL FILE%GET('soiltype',SELF_DUST%SOILTYPE)
  CALL FILE%GET('soilph1', SELF_DUST%SOILPH1)
  CALL FILE%GET('soilph2', SELF_DUST%SOILPH2)
  CALL FILE%GET('soilph3', SELF_DUST%SOILPH3)
  CALL FILE%GET('soilph4', SELF_DUST%SOILPH4)
  CALL FILE%GET('soilph5', SELF_DUST%SOILPH5)
  CALL FILE%GET('z0am', SELF_DUST%Z0AM)
  CALL FILE%GET('area', SELF_DUST%AREA)
  CALL FILE%GET('z0m', SELF_DUST%Z0M)

  SELF_DUST%NLAT = SIZE(SELF_DUST%LATD)
  SELF_DUST%LAT1 = SELF_DUST%LATD(1) * RPI / 180.0_JPRB                        !rads
  SELF_DUST%DLAT = (SELF_DUST%LATD(2)-SELF_DUST%LATD(1)) * RPI / 180.0_JPRB    ! delta in rads

  IF (SELF_DUST%LOND(1) < 0) THEN
     WRITE(NULERR,*) "THE LON SHOULD BE 0- 360 THE CURRENT FILE LON ARE -180 to 180"
    ! SELF_DUST%LOND = MOD(SELF_DUST%LOND(:) +180.0,360.0)
  ELSE
     SELF_DUST%LOND = SELF_DUST%LOND
  ENDIF
  SELF_DUST%NLON = SIZE(SELF_DUST%LOND)
  SELF_DUST%LON1 = SELF_DUST%LOND(1) * RPI / 180.0_JPRB                        !rad
  SELF_DUST%DLON = (SELF_DUST%LOND(2)-SELF_DUST%LOND(1)) * RPI / 180.0_JPRB    !delta in rads
  
  ! Check dimensions
  IF (    SIZE(SELF_DUST%Z0M,1) /= SELF_DUST%NLON .OR. &
       &  SIZE(SELF_DUST%Z0M,2) /= SELF_DUST%NLAT .OR. &
       &  SIZE(SELF_DUST%Z0M,3) /= IMONTH) THEN
    WRITE(NULERR,*) 'Aerosols in', CL_FILE_NAME, 'must be dimensioned LON,LAT,MONTH (', &
         &  ILON, ",", ILAT, ",", IMONTH, ")"
    CALL ABOR1("Error reading aerosol climatology NetCDF file")
  ENDIF
  SELF_DUST%NMONTH= SIZE(SELF_DUST%Z0M,3)

  CALL FILE%CLOSE()

IF (LHOOK) CALL DR_HOOK('YOEDUST:SU_AER_CLIMATOLOGY',1,ZHOOK_HANDLE)

END SUBROUTINE SU_DUST_FIELDS

SUBROUTINE SU_DUST_FIELDS_INTERP(SELF, KSTART, KEND, KCOL, PLAT, PLON, &
                                  ISOILPH1, ISOILPH2, ISOILPH3, ISOILPH4, ISOILPH5, &
                                  IZ0AM, IPOTSRC, ISOILTYPE, IAREA, ICULT, IZ0M, IFPAR, IM0,ILAI_MAX,ILAI_AVG )

  USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK
  IMPLICIT NONE
  CLASS(TEAERC_DUST), INTENT(INOUT) :: SELF
  INTEGER(KIND=JPIM), INTENT(IN) :: KCOL
  INTEGER(KIND=JPIM), INTENT(IN) :: KSTART, KEND
  INTEGER(KIND=JPIM), INTENT(IN) :: IM0 
  ! Sine of latitude of input columns
  !REAL(KIND=JPRB) :: PSINLAT(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(IN) :: PLAT(KCOL)  !rads = PGELAT
  REAL(KIND=JPRB), INTENT(IN) :: PLON(KCOL)  !rads = PGELAM
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  REAL(KIND=JPRB), INTENT(OUT) :: &
  ISOILPH1(KCOL), ISOILPH2(KCOL), ISOILPH3(KCOL), ISOILPH4(KCOL), ISOILPH5(KCOL), &
  IZ0AM(KCOL), IPOTSRC(KCOL), IAREA(KCOL), ICULT(KCOL)
  REAL(KIND=JPRB),  INTENT(OUT) :: ILAI_MAX(KCOL), ILAI_AVG(KCOL)
  REAL(KIND=JPRB),  INTENT(OUT) :: IZ0M(KCOL), IFPAR(KCOL)
  !INTEGER(KIND=JPIM), INTENT(OUT) :: ISOILTYPE(KSTART:KEND)  
  REAL(KIND=JPRB),  INTENT(OUT) :: ISOILTYPE(KSTART:KEND)

  #include "abor1.intfb.h"
  
  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION main call',0,ZHOOK_HANDLE)

  
  ! Interpolation calls with corrected array assignments
  ! Interpolation calls with full array assignments
CALL INTP_SOILT(SELF, SELF%SOILTYPE, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILTYPE)
SELF%TSOILTYPE(:) = ISOILTYPE(:)

CALL INTP_SOILT(SELF, SELF%AREA, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IAREA)
SELF%TAREA(:) = IAREA(:)

CALL INTP_SOILT(SELF, SELF%SOILPH1, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH1)
SELF%TSOILPH1(:) = ISOILPH1(:)

CALL INTP_SOILT(SELF, SELF%SOILPH2, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH2)
SELF%TSOILPH2(:) = ISOILPH2(:)

CALL INTP_SOILT(SELF, SELF%SOILPH3, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH3)
SELF%TSOILPH3(:) = ISOILPH3(:)

CALL INTP_SOILT(SELF, SELF%SOILPH4, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH4)
SELF%TSOILPH4(:) = ISOILPH4(:)

CALL INTP_SOILT(SELF, SELF%SOILPH5, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH5)
SELF%TSOILPH5(:) = ISOILPH5(:)

CALL INTP_SOILT(SELF, SELF%Z0AM, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IZ0AM)
SELF%TZ0AM(:) = IZ0AM(:)

CALL INTP_SOILT(SELF, SELF%POTSRC, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IPOTSRC)
SELF%TPOTSRC(:) = IPOTSRC(:)

CALL INTP_SOILT(SELF, SELF%CULT, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ICULT)
SELF%TCULT(:) = ICULT(:)

CALL INTP_SOILT(SELF, SELF%LAI_MAX, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ILAI_MAX)
SELF%TLAI_MAX(:) = ILAI_MAX(:)

CALL INTP_SOILT(SELF, SELF%LAI_AVG, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ILAI_AVG)
SELF%TLAI_AVG(:) = ILAI_AVG(:)

CALL INTP_SOILT(SELF, SELF%FPAR(:,:,IM0), KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IFPAR)
SELF%TFPAR(:) = IFPAR(:)

CALL INTP_SOILT(SELF, SELF%Z0M(:,:,IM0), KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IZ0M)
SELF%TZ0M(:) = IZ0M(:)

  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS main call',1,ZHOOK_HANDLE)

CONTAINS 

SUBROUTINE INTP_SOILT(SELF,FIELD2D, KSTART, KEND,KCOL, PLAT, PLON, INTERSOILT)

  USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK
  USE YOMLUN    , ONLY : NULOUT
  REAL(KIND=JPRB),    INTENT(IN) :: FIELD2D(:,:)
  INTEGER(KIND=JPIM), INTENT(IN) :: KCOL
  CLASS(TEAERC_DUST), INTENT(IN) :: SELF
  INTEGER(KIND=JPIM), INTENT(IN) :: KSTART, KEND
  REAL(KIND=JPRB) :: PSINLAT(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(IN) :: PLAT(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(IN) :: PLON(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(OUT) :: INTERSOILT (KSTART:KEND)
  
  INTEGER(KIND=JPIM), DIMENSION(KSTART:KEND) :: KLAT1, KLAT2, KLON1, KLON2
  REAL(KIND=JPRB), DIMENSION(KSTART:KEND) :: PLATWEIGHT, PLONWEIGHT
  INTEGER(KIND=JPIM) :: JL
  REAL(KIND=JPRB) :: ZLAT(KSTART:KEND)
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  REAL(KIND=JPRB) :: ZAERA, ZAERB
  !C. Perez
  INTEGER(KIND=JPIM) :: I_INX, J_INX
  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS SOILTYPE',0,ZHOOK_HANDLE)

  PLATWEIGHT = 0.0
  PLONWEIGHT = 0.0
  ! Longitude interpolation points and weights
  PLONWEIGHT = 1.0_JPRB + (PLON - SELF%LON1) / SELF%DLON
  KLON1 = MAX(1, MIN(INT(PLONWEIGHT), SELF%NLON))
  KLON2 = MOD(KLON1,SELF%NLON)+1 ! Correct treatment of dateline
  PLONWEIGHT = PLONWEIGHT - KLON1

  !ZLAT = ASIN(PSINLAT)
  PSINLAT=SIN(PLAT) ! SIN of rads
  ZLAT = PLAT !RADS
  PLATWEIGHT = 1.0_JPRB + (ZLAT - SELF%LAT1) / SELF%DLAT
!  KLAT1 = MAX(0, MIN(INT(PLATWEIGHT), SELF%NLAT-1))  !C. Perez: Why 0? Does the latitude indexing start in 0? 
  KLAT1 = MAX(1, MIN(INT(PLATWEIGHT), SELF%NLAT-1))
  KLAT2 = KLAT1+1

  ! Interpolation in sin(latitude)
  PLATWEIGHT = (PSINLAT - SIN(SELF%LAT1+(KLAT1-1)*SELF%DLAT)) &
       &     / (SIN(SELF%LAT1+(KLAT2-1)*SELF%DLAT) - SIN(SELF%LAT1+(KLAT1-1)*SELF%DLAT))

  DO JL = KSTART,KEND
  !C.Perez
  !choose the closer longitude corner
  IF (PLONWEIGHT(JL) > 0.5_JPRB) THEN
      I_INX = KLON2(JL)
    ELSE
      I_INX = KLON1(JL)
    END IF
   !choose the closer latitude  corner
  IF (PLATWEIGHT(JL) > 0.5_JPRB) THEN
      J_INX = KLAT2(JL)
    ELSE
      J_INX = KLAT1(JL)
    END IF
  
   INTERSOILT(JL) = FIELD2D(I_INX, J_INX)
   !C. Perez
  END DO
  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS SOILTYPE',1,ZHOOK_HANDLE)
END SUBROUTINE INTP_SOILT

END SUBROUTINE SU_DUST_FIELDS_INTERP

SUBROUTINE CLEANUP_DUST_CLIM(SELF)
 
  !-----------------------------------------------------------------------
  ! Purpose: Deallocate interpolated output arrays (T* arrays)
  ! Note: Climatology data (CULT, FPAR, etc.) is NOT deallocated
  ! to allow reuse without reloading NetCDF file.
  ! Call this after each interpolation to free T* memory.
  !-----------------------------------------------------------------------


  CLASS(TEAERC_DUST), INTENT(INOUT) :: SELF
  
  
  ! Deallocate interpolated output arrays
  IF (ALLOCATED(SELF%TCULT))     DEALLOCATE(SELF%TCULT)
  IF (ALLOCATED(SELF%TSOILTYPE)) DEALLOCATE(SELF%TSOILTYPE)
  IF (ALLOCATED(SELF%TPOTSRC))   DEALLOCATE(SELF%TPOTSRC)
  IF (ALLOCATED(SELF%TAREA))     DEALLOCATE(SELF%TAREA)
  IF (ALLOCATED(SELF%TZ0AM))     DEALLOCATE(SELF%TZ0AM)
  IF (ALLOCATED(SELF%TSOILPH1))  DEALLOCATE(SELF%TSOILPH1)
  IF (ALLOCATED(SELF%TSOILPH2))  DEALLOCATE(SELF%TSOILPH2)
  IF (ALLOCATED(SELF%TSOILPH3))  DEALLOCATE(SELF%TSOILPH3)
  IF (ALLOCATED(SELF%TSOILPH4))  DEALLOCATE(SELF%TSOILPH4)
  IF (ALLOCATED(SELF%TSOILPH5))  DEALLOCATE(SELF%TSOILPH5)
  IF (ALLOCATED(SELF%TZ0M))      DEALLOCATE(SELF%TZ0M)
  IF (ALLOCATED(SELF%TFPAR))     DEALLOCATE(SELF%TFPAR)
  IF (ALLOCATED(SELF%TLAI_MAX))  DEALLOCATE(SELF%TLAI_MAX)
  IF (ALLOCATED(SELF%TLAI_AVG))  DEALLOCATE(SELF%TLAI_AVG)
  
  ! Reset logical flags
  SELF%IS_INTERPOLATED = .FALSE.
  
  WRITE(NULOUT,*) 'DUST CLIMATOLOGY ARRAYS T DEALLOCATED'
  
END SUBROUTINE CLEANUP_DUST_CLIM


END MODULE YOEDUST
